### ISSUE TITLE
Update the data of detail weather page.

### ISSUE THREAD

**Issue by Desgard** [Desgard/Calendouer-iOS#21]
> [Project]/App/Controller/detail/WeatherDetailViewController.swift

This view controller needs to get the newest data in these two cells. 
Add a `updateData()` function to achieved. And call back the `tableView` -> `reloadData()`

## API function:

> [Project]/App/Tools/ProcessManager.swift

+ ProcessManager -> `Get3DaysWeather`
+ ProcessManager -> `GetLifeScore`

**Comment by SeaHub** [comment]
Feature has been realized in this [commit](https://github.com/Desgard/Calendouer-iOS/commit/5cd6c03e75eb9a4d67a2510224876a7a9a8b7bb6)
