### ISSUE TITLE
Add a button to refresh weather detail page msg

### ISSUE THREAD

**Issue by Desgard** [Desgard/Calendouer-iOS#24]
![default](https://cloud.githubusercontent.com/assets/7804535/25393715/ca6cd8c4-2a0e-11e7-999b-be71a41885db.png)

**Comment by SeaHub** [comment]
Feature has been realized in this [commit](https://github.com/Desgard/Calendouer-iOS/commit/c253ee081028e2d67ae06c99670e3c9d5ff3b72a)
